example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
# TODO: Implement Routings Here
from django.urls import path
from katalog.views import index

app_name = 'katalog'

urlpatterns = [
    path('', index, name='index'),
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import show_mywatchlist
from mywatchlist.views import show_xml
from mywatchlist.views import show_json
from mywatchlist.views import show_json_by_id
from mywatchlist.views import show_xml_by_id

app_name = 'mywatchlist'

urlpatterns = [
    path('html/', show_mywatchlist, name='show_mywatchlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import show_todolist

from todolist.views import register

from todolist.views import login_user 

from todolist.views import logout_user

from todolist.views import create_task

from todolist.views import get_task

from todolist.views import add_task

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', create_task, name='create_task'),
    path('json/', get_task, name='get_task'),
    path('add/', add_task, name='add_task'),
]

example_app/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.utils import timezone
from datetime import datetime, date

class Person(models.Model):
    display_name = models.CharField(max_length = 30)
    display_npm = models.CharField(max_length = 10)

class Post(models.Model):
    author = models.ForeignKey(Person, on_delete = models.CASCADE)
    content = models.CharField(max_length = 125)
    published_date = models.DateTimeField(default = timezone.now)

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

# Create your models here.
class MyWatchList(models.Model):
    watched = models.TextField()
    title = models.TextField()
    rating = models.IntegerField()
    release_date = models.TextField()
    review = models.TextField()

todolist/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    date = models.TextField()
    title = models.TextField()
    description = models.TextField()

todolist/forms.py
from django import forms

class TaskBaru(forms.Form):
    judul = forms.CharField(label='Judul', max_length=100)
    deskripsi = forms.CharField(label='Deskripsi', max_length=100)

example_app/views.py
from django.shortcuts import render

from example_app.models import Person

def index(request):
    persons = Person.objects.all()
    response = {'name' : 'Akbar Firdaus', 'npm' : '2106651856', 'persons' : persons}
    return render(request, 'index.html', response)

katalog/views.py
from django.shortcuts import render

# TODO: Create your views here.
from katalog.models import CatalogItem

def index(request):
    barang_katalog = CatalogItem.objects.all()
    response = {'barang_katalog' : barang_katalog}
    return render(request, 'katalog.html', response)

mywatchlist/views.py
from django.shortcuts import render
from mywatchlist.models import MyWatchList

from django.http import HttpResponse
from django.core import serializers

# Create your views here.
def show_mywatchlist(request):
    data_barang_mywatchlist = MyWatchList.objects.all()
    context = {
    'list_watchlist': data_barang_mywatchlist,
    'nama': 'Akbar Firdaus'
    }
    return render(request, "mywatchlist.html", context)

def show_xml(request):
    data = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request, id):
    data = MyWatchList.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = MyWatchList.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

todolist/views.py
from turtle import title
from django.http import HttpResponse, HttpResponseNotFound

from webbrowser import get
from django.shortcuts import render

from django.core import serializers

# Create your views here.
from todolist.models import Task

from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages

from django.contrib.auth import authenticate, login

from django.contrib.auth import logout

from django.contrib.auth.decorators import login_required

import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse

from django.shortcuts import render

from todolist.forms import TaskBaru

@login_required(login_url='/todolist/login/')
def show_todolist(request):
    data_barang_todolist = Task.objects.all()
    context = {'list_todolist': data_barang_todolist,
                'nama': 'Akbar Firdaus',
                    'last_login': request.COOKIES['last_login'],
                        'task_baru': TaskBaru(request.POST),
                        }
    return render(request, "todolist.html", context)

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("todolist:show_todolist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

def create_task(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = TaskBaru(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect('/todolist/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = TaskBaru()

    return render(request, 'name.html', {'form': form})

def get_task(request):
    task = Task.objects.all()
    return HttpResponse(serializers.serialize('json', task))

def add_task(request):
    if request.method == 'POST':
        date = request.COOKIES['last_login']
        title = request.POST.get("nama_barang")
        description = request.POST.get("nama_barang")

        new_task = Task(date = date, title = title, description = description)
        new_task.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>Nama saya adalah {{ name }} dengan NPM {{ npm }} </h3>

  {% if persons %}
    {% for person in persons %}
      {{ person.display_name }} - {{ person.display_npm }}
      <br>
    {% endfor %}
  {% endif %}

{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: Akbar Firdaus</h5>

  <h5>Student ID: 2106651856</h5>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% if barang_katalog %}
      {% for barang in barang_katalog %}
        <tr>
        <td> {{ barang.item_name }} </td>
        <td> {{ barang.item_price }} </td>
        <td> {{ barang.item_stock }} </td>
        <td> {{ barang.rating }} </td>
        <td> {{ barang.description }} </td>
        <td> {{ barang.item_url }} </td>
        </tr>
      {% endfor %}
    {% endif %}
  </table>

 {% endblock content %}

mywatchlist/templates/mywatchlist.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 2 Assignment PBP/PBD</h1>

  <h5>Name: Akbar Firdaus</h5>

  <h5>Student ID: 2106651856</h5>

  <table>
    <tr>
      <th>Watched</th>
      <th>Title</th>
      <th>Rating</th>
      <th>Release Date</th>
      <th>Review</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% if list_watchlist %}
      {% for film in list_watchlist %}
        <tr>
        <td> {{ film.watched }} </td>
        <td> {{ film.title }} </td>
        <td> {{ film.rating }} </td>
        <td> {{ film.release_date }} </td>
        <td> {{ film.review }} </td>
        </tr>
      {% endfor %}
    {% endif %}
  </table>

 {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  
  <!-- Acknowledgement -->
  <!-- https://stackoverflow.com/questions/63174850/how-to-add-animation-to-a-bootstrap-4-card-on-hover -->
  <!-- https://www.youtube.com/watch?v=9Dp1X1UYz6Q&ab_channel=WEBSOLUTIONS -->

  <style>
    .ho:hover {
      transform: scale(1.1);
    }
  </style>
  
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  {% block content %}
  {% endblock content %}
</body>

</html>

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<!-- <div class="d-flex justify-content-center">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Login</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        </ul>
        </div>
    </nav>
</div> -->

<div class="d-flex justify-content-center">
    <div class = "login">

        <h1>LOGIN</h1>

        <form method="POST" action="">
            {% csrf_token %}
            <table>
                <tr>
                    <td>Username: </td>
                    <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                </tr>
                        
                <tr>
                    <td>Password: </td>
                    <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                </tr>

                <tr>
                    <td></td>
                    <td><input class="btn login_btn" type="submit" value="Login"></td>
                </tr>
            </table>
        </form>

        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}     
            
        Belum mempunyai akun? <a href="{% url 'todolist:register' %}">Buat Akun</a>

    </div>
</div>

{% endblock content %}

todolist/templates/name.html
<h1>Create-task</h1>

<form action="/todolist/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class="d-flex justify-content-center">
    <div class = "login">
        
        <h1>Formulir Registrasi</h1>  

            <form method="POST" >  
                {% csrf_token %}  
                <table>  
                    {{ form.as_table }}  
                    <tr>  
                        <td></td>
                        <td><input type="submit" name="submit" value="Daftar"/></td>  
                    </tr>  
                </table>  
            </form>

        {% if messages %}  
            <ul>   
                {% for message in messages %}  
                    <li>{{ message }}</li>  
                    {% endfor %}  
            </ul>   
        {% endif %}

    </div>  
</div>
{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

 {% block content %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Tugas 5 Assignment PBP/PBD</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
          <a class="nav-link" href="#">Hello, {{nama}}</a>
      </li>
      <li class="nav-item">
          <a class="nav-link" href="#">Student ID: 2106651856</a>  
      </li>
    </ul>
  </div>
</nav>

<!-- Acknowledgement -->
<!-- https://getbootstrap.com/docs/4.0/components/card/ -->
<!-- https://www.geeksforgeeks.org/flexbox-utilities-in-bootstrap-with-examples/ -->

<h1>Todo List</h1>

<div class="d-flex p-2">
  <div class="card ho" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">This is test title-1</h5>
      <h6 class="card-subtitle mb-2 text-muted">This is date-1</h6>
      <p class="card-text">lorem ipsum dolor sit amet</p>
    </div>
  </div>
  <div class="card ho" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">This is test title-2</h5>
      <h6 class="card-subtitle mb-2 text-muted">This is date-1</h6>
      <p class="card-text">lorem ipsum dolor sit amet</p>
    </div>
  </div>
  <div class="card ho" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">This is test title-3</h5>
      <h6 class="card-subtitle mb-2 text-muted">This is date-3</h6>
      <p class="card-text">lorem ipsum dolor sit amet</p>
    </div>
  </div>
  <div class="card ho" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">This is test title-4</h5>
      <h6 class="card-subtitle mb-2 text-muted">This is date-4</h6>
      <p class="card-text">lorem ipsum dolor sit amet</p>
    </div>
  </div>
  <div class="card ho" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">This is test title-5</h5>
      <h6 class="card-subtitle mb-2 text-muted">This is date-5</h6>
      <p class="card-text">lorem ipsum dolor sit amet</p>
    </div>
  </div>
  <div class="card ho" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">This is test title-6</h5>
      <h6 class="card-subtitle mb-2 text-muted">This is date-6</h6>
      <p class="card-text">lorem ipsum dolor sit amet</p>
    </div>
  </div>
</div>

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Task</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Add a new task!</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form>
          <div class="mb-3">
            <label for="judul-task" class="col-form-label">Judul:</label>
            <input type="text" class="form-control" id="judul-task">
          </div>
          <div class="mb-3">
            <label for="deskripsi-task" class="col-form-label">Deskripsi:</label>
            <textarea class="form-control" id="deskripsi-task"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="submit-button">Submit</button>
      </div>
    </div>
  </div>
</div>

  <table>
    <tr>
      <th>Date</th>
      <th>Title</th>
      <th>Description</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}

    {% if task_baru %}
      {% for isi in task_baru %}
        <tr>
        <td> {{ isi.judul }} </td>
        <td> {{ isi.deskripsi }} </td>
        </tr>
      {% endfor %}
    {% endif %}
  </table>

  <h5>Sesi terakhir login: {{ last_login }}</h5>

  <button><a href="{% url 'todolist:create_task' %}">Tambah Task Baru</a></button>

  <button><a href="{% url 'todolist:logout' %}">Logout</a></button>


 {% endblock content %}